---

user_agent: 'polldit: predicting poll results based on reddit sentiment (by /u/nflans)'

reddit_url: "www.reddit.com"

db:
    name:       "polldit_db"
    user:       root
    password:   root
    address:    "127.0.0.1"

subreddits:
    - 'politics'
    - 'usnews'
    - '2016elections'
    - 'news'
    - 'uspolitics'
    - 'government'
    - 'americangovernment'

candidates:
    sanders:
        - 'bernie'
        - 'sanders'
        - 'bern'
    clinton:
        - 'hillary'
        - 'clinton'
        - 'hrc'
        - 'hilary' # intentional common misspelling
    omalley:
        - "martin"
        - "o'malley"
        - "omalley"
    bush:
        - 'jeb'
        - 'bush'
    carson:
        - 'ben'
        - 'carson'
    christie:
        - 'chris'
        - 'christie'
    cruz:
        - 'ted'
        - 'cruz'
    trump:
        - 'donald'
        - 'trump'
    fiorina:
        - 'carly'
        - 'fiorina'
    kasich:
        - 'jon'
        - 'kasich'
    paul:
        - 'rand'
        - 'paul'
    rubio:
        - 'marco'
        - 'rubio'
    santorum:
        - 'rick'
        - 'santorum'
