---

user_agent: 'polldit: predicting poll results based on reddit sentiment (by /u/nflans)'

reddit_url: "www.reddit.com"

subreddits:
    - 'politics'
    - 'usnews'
    - '2016elections'
    - 'news'
    - 'uspolitics'
    - 'government'
    - 'americangovernment'

candidates:
    sanders:
        - 'bernie sanders'
        - 'bernie'
        - 'sanders'
        - 'bern'
    clinton:
        - 'hillary clinton'
        - 'hillary'
        - 'clinton'
        - 'hilary' # intentional common misspelling
    trump:
        - 'donald trump'
        - 'donald'
        - 'trump'
